variables:
  SIMPLEIPTV_VERSION: "1.0.1"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - tagging
  - build
  - deploy

Tagging from pipeline:
  stage: tagging
  timeout: 30m
  tags:
    - linux
  script:
    - scripts/bump_version.sh
  only:
    - master
  artifacts:
    paths:
      - version.txt

linux-job:
  stage: build
  timeout: 5h
  tags:
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - master
  artifacts:
    paths:
      - packages/
  script:
    - echo "Compiling the code..."
    - scripts/build_linux.sh
    - echo "Compile complete."

windows-job:
  stage: build
  timeout: 10h
  tags:
    - windows
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - master
  artifacts:
    paths:
      - packages/
  script:
    - scripts/build_windows.ps1

publish:
  stage: deploy
  tags:
    - linux
  needs:
    - job: Tagging from pipeline
      artifacts: true
    - job: linux-job
      artifacts: true
    - job: windows-job
      artifacts: true
  script: |
    set -x
    VERSION=$(cat version.txt)
    echo "Publishing artifacts for version $VERSION..."

    for f in packages/*; do
      if [ -f "$f" ]; then
        filename=$(basename "$f")
        full_path=$(realpath "$f")
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
         --upload-file "$full_path" \
         "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/simpleiptv/${VERSION}/${filename}"
        echo "Uploaded: $full_path -> $filename"
      fi
    done

